Assets/_BForBoss/Scripts.meta
Assets/_BForBoss/_Character/InputActions.meta
Assets/_BForBoss/_Character/InputActions/BFB_FirstPerson_InputActions.inputactions
Assets/_BForBoss/_Character/InputActions/BFB_FirstPerson_InputActions.inputactions.meta
Assets/_BForBoss/_Character/Prefabs/PlayerRoot.prefab
Assets/_BForBoss/_Character/Scenes/Sandbox.unity
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.cs
Assets/_BForBoss/_Character/Scripts/PlayerDashBehaviour.cs
Assets/_BForBoss/_Character/Scripts/PlayerDashBehaviour.cs.meta

https://perigongames.atlassian.net/browse/BFB-33
- Added Separate Script to add Dash functionality
- Created a BFB Input action for Dash
- The Logic is mostly from the Sample - simple Dash, with a bit of Advanced Dash mixed in
- Architecture:
- Passed in base `Character` and a `Func<Vector2>` into the Dash Component. 
These are the main components Dash is based off of. `Character` will rarely change, so passing that in is best. 
Video: 
https://www.youtube.com/watch?v=L4rPZK5ROeA

BFB-33: Added Dash Mechanic

---

Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.InputSettings.cs

https://perigongames.atlassian.net/browse/BFB-68
Fixed Default inverted setting

BFB-68: Fixed Default inverse settings

---

Assets/_BForBoss/Scripts/Managers/WorldManager.cs
Assets/_BForBoss/_Analytics/Scripts/PerigonAnalytics.cs
Assets/_BForBoss/_Leaderboard/Scripts/InputUsernameViewBehaviour.cs
Assets/_BForBoss/_Leaderboard/Scripts/Leaderboard.asmdef

https://perigongames.atlassian.net/browse/BFB-64
- uses the username saved in Playerprefs (if already exists)
- if not, will set the username once the player clicks save on the panel

BFB-64: Set username property

---

Assets/_BForBoss/Scripts/InputSettingsViewBehaviour.cs
Assets/_BForBoss/_Analytics/Scripts/PerigonAnalytics.cs
Assets/_BForBoss/_Leaderboard/Scripts/InputUsernameViewBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-65
- set control settings for mouse and controller in InputSettings view model
- not sure where else I should set the control settings property
- also a bug fix where if the user was deleted from mixpanel BUT was already set in PlayerPrefs, a new user would be created but the username would need be saved to the mixpanel profile

BFB-65: Set controller settings property

---

Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.InputSettings.cs

https://perigongames.atlassian.net/browse/BFB-68
- Fixed default invert settings
- Fixed changing invert settings

BFB-68: Fix inverted settings

---

Assets/_BForBoss/Scripts/DeathAreaBehaviour.cs
Assets/_BForBoss/Scripts/Managers/CheckpointManager.cs
Assets/_BForBoss/_Leaderboard/Scripts/LeaderboardPanelBehaviour.cs
Assets/_BForBoss/_Leaderboard/Scripts/Networking/DreamloSendScoreEndPoint.cs

https://perigongames.atlassian.net/browse/BFB-82
- Fix for the leaderboard to be stored
- When you finish the race, and jump off, you now reset to the beginning
- The last checkpoint only sends the score ONCE on end game

BFB-82: Fix leaderboard scores

---

Assets/_BForBoss/Scripts/Managers/WorldManager.cs
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.InputSettings.cs

https://perigongames.atlassian.net/browse/BFB-68
- Finally hopefully third times the charm to fix this

BFB-68: Mouse inverted fix

---

Assets/Robot Kyle/Materials/Robot_Color.mat
Assets/Robot Kyle/Model/Robot Kyle.fbx.meta
Assets/_BForBoss/_Character/CharacterController.controller
Assets/_BForBoss/_Character/CharacterController.controller.meta
Assets/_BForBoss/_Character/InputActions/BFB_FirstPerson_InputActions.inputactions
Assets/_BForBoss/_Character/Prefabs/PlayerRoot.prefab
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.Animator.cs
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.Animator.cs.meta
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.cs
Assets/_BForBoss/_Character/Scripts/PlayerWallRunBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-61
Also includes a first pass at 
https://perigongames.atlassian.net/browse/BFB-69
Allow switching to a third person view, and toggling back and forth. Currently you can switch via either a toggle in the inspector, or by pressing 'Q' (I didn't bother adding a controller binding, but thats an easy change if we do want it).
Also includes basic animations, wall running animations are very much WIP and dash and slide aren't in at all, but the basics are there.
https://youtu.be/01-082Eoiug

BFB-61 : Support Third Person View

---

Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.Animator.cs
Assets/_BForBoss/_Character/Scripts/PlayerWallRunBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-71
Wall run animations - currently just using the turn/strafe animations already set up, but so that the player is constantly strafing away from the wall. Looks more compelling than it sounds.
Also added some line breaks to wall running 
https://youtu.be/O8wy2uvXuGM

Setup wall running animations

---

Assets/_BForBoss/Scripts/FreezeActionsUtility.cs
Assets/_BForBoss/Scripts/FreezeActionsUtility.cs.meta
Assets/_BForBoss/Scripts/LockMouseUtility.cs
Assets/_BForBoss/Scripts/Managers/WorldManager.cs
Assets/_BForBoss/Scripts/UI/PauseMenu.cs
Assets/_BForBoss/Scripts/UserInterface/SettingsViewBehaviour.cs
Assets/_BForBoss/Scripts/UserInterface/TabbedPanelViewBehaviour.cs
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.InputSettings.cs
Assets/_BForBoss/_Character/Scripts/PlayerDashBehaviour.cs
Assets/_BForBoss/_Leaderboard/LeaderboardPanel.prefab
Assets/_BForBoss/_Leaderboard/Row.prefab
Assets/_BForBoss/_Leaderboard/Scripts/ILockMouseInput.cs
Assets/_BForBoss/_Leaderboard/Scripts/LeaderboardPanelBehaviour.cs
Assets/_BForBoss/_Leaderboard/Scripts/LeaderboardRowBehaviour.cs
Assets/_BForBoss/_Leaderboard/Scripts/Networking/DreamloGetLeaderboardEndPoint.cs
Assets/_BForBoss/_Leaderboard/Scripts/Username/ForcedSetUsernameViewBehaviour.cs
Assets/_BForBoss/_Leaderboard/Scripts/Username/SetUsernameViewBehaviour.cs
Assets/_BForBoss/_Leaderboard/Scripts/Username/SetUsernameViewModel.cs

https://perigongames.atlassian.net/browse/BFB-90
- Placing Leaderboard into settings
- Abstracting Locking Controls when menu is open

BFB-90: Putting leaderboard into settings

---

Assets/_BForBoss/_Character/FPS_Camera_Blends.asset
Assets/_BForBoss/_Character/Prefabs/PlayerRoot.prefab
Assets/_BForBoss/_Character/Scripts/Character.asmdef
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.Animator.cs
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.cs
Assets/_BForBoss/_Character/Scripts/PlayerWallRunBehaviour.cs
ProjectSettings/TagManager.asset

https://perigongames.atlassian.net/browse/BFB-93
Cull body visibility when in third person, and modify switching so that animation continues during the transition
I also fixed a bug to do with switching views well wall running that was somewhat related.

Fix for Body Visibility Bug

---

Assets/_BForBoss/Scripts/UserInterface/GameplaySettingsViewBehaviour.cs
Assets/_BForBoss/_Analytics/Scripts/PerigonAnalytics.cs

https://perigongames.atlassian.net/browse/BFB-96
Add analytics to capture POV settings for each user

add POV analytics

---

Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.cs
Assets/_BForBoss/_Leaderboard/Scripts/Username/InputUsername.cs
Assets/_BForBoss/_Leaderboard/Scripts/Username/SetUsernameViewBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-102
Limits the username to be only alpha numeric.
This regex should now allow alpha number + space

BFB-102: Limit the username

---

Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.cs
Assets/_BForBoss/_Character/Scripts/PlayerWallRunBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-54
Now correctly resets the jump count, will be at 1 when the user jumps out of the wall but 0 otherwise

Wall run bugfix

---

Assets/_BForBoss/_Leaderboard/Scripts/LeaderboardPanelBehaviour.cs
Assets/_BForBoss/_Leaderboard/Scripts/UploadPlayerScoreDataSource.cs
Assets/_BForBoss/_Leaderboard/Scripts/Username/InputUsername.cs
Assets/_BForBoss/_Leaderboard/Scripts/Username/SetUsernameViewModel.cs
Assets/_BForBoss/_Utility/Scripts/PlayerPrefKeys.cs

https://perigongames.atlassian.net/browse/BFB-125
Moved leaderboard player pref struct into Perigon.Utility.PlayerPrefKeys - this is important, as otherwise the username is not listed in the player pref debug tool

Move leaderboard player prefs

---

Assets/_BForBoss/_Core/Scripts/Managers/GunRangeWorldManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/GunRangeWorldManager.cs.meta
Assets/_BForBoss/_Core/Scripts/UserInterface/SettingsViewBehaviour.cs
Assets/_BForBoss/_Weapons.meta
Assets/_BForBoss/_Weapons/Scenes.meta
Assets/_BForBoss/_Weapons/Scenes/GunRange.unity
Assets/_BForBoss/_Weapons/Scenes/GunRange.unity.meta
ProjectSettings/EditorBuildSettings.asset

https://perigongames.atlassian.net/browse/BFB-121
- Created a weapon range

BFB-121: Gun Range Scene

---

Assets/_BForBoss/Tests/Mocks/MockWeaponProperties.cs
Assets/_BForBoss/Tests/Tools/TestUtilities.cs
Assets/_BForBoss/Tests/WeaponTests.cs
Assets/_BForBoss/_Weapons/Scenes/GunRange.unity
Assets/_BForBoss/_Weapons/Scripts/AutomaticWeaponBehaviour.cs
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/AutoRifle.asset
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Shotgun.asset
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Shotgun.asset.meta
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/WeaponScriptableObject.cs
Assets/_BForBoss/_Weapons/Scripts/SemiAutomaticWeaponBehaviour.cs
Assets/_BForBoss/_Weapons/Scripts/Weapon.cs
Assets/_BForBoss/_Weapons/Scripts/WeaponBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-137
- Shoot multiple bullets at once

BFB-137: Multiple bullets

---

Assets/_BForBoss/Tests/CharacterSlideTests.cs
Assets/_BForBoss/Tests/CharacterWallRunTests.cs
Assets/_BForBoss/Tests/CharacterWallRunTests.cs.meta
Assets/_BForBoss/Tests/Scenes/CharacterWallRunTest.unity
Assets/_BForBoss/Tests/Scenes/CharacterWallRunTest.unity.meta

https://perigongames.atlassian.net/browse/BFB-95
- Added Test Scene for wall running
- Added tests for wall running
- Not every case is added, but the base is there

BFB-95: Test cases for wall running

---

Assets/_BForBoss/Tests/InputSettingsViewModelTests.cs
Assets/_BForBoss/Tests/InputSettingsViewModelTests.cs.meta
Assets/_BForBoss/Tests/Mocks/MockAnalytics.cs
Assets/_BForBoss/Tests/Mocks/MockAnalytics.cs.meta
Assets/_BForBoss/Tests/Mocks/MockInputSettings.cs
Assets/_BForBoss/Tests/Mocks/MockInputSettings.cs.meta
Assets/_BForBoss/Tests/Tests.asmdef
Assets/_BForBoss/_Analytics/Scripts/PerigonAnalytics.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/InputSettingsViewBehaviour.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/InputSettingsViewModel.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/InputSettingsViewModel.cs.meta

https://perigongames.atlassian.net/browse/BFB-92
- Mocks for Analytics
- Mocks for IInputSettings

BFB-92:  Testing for InputSettingsViewModel

---

Assets/_BForBoss/_Entities/Materials.meta
Assets/_BForBoss/_Entities/Materials/Robot_Dissolve.mat
Assets/_BForBoss/_Entities/Materials/Robot_Dissolve.mat.meta
Assets/_BForBoss/_Entities/Prefabs/Dummy.prefab
Assets/_BForBoss/_Entities/Scripts/DummyTargetBehaviour.cs
Assets/_BForBoss/_Entities/Scripts/LifeCycleBehaviour.cs
Assets/_BForBoss/_Entities/Scripts/ScriptableObjects/HealthProperties.asset
Assets/_BForBoss/_Entities/Shaders.meta
Assets/_BForBoss/_Entities/Shaders/DissolveGraph.shadergraph
Assets/_BForBoss/_Entities/Shaders/DissolveGraph.shadergraph.meta

https://perigongames.atlassian.net/browse/BFB-117
Add dissolve fade out integrated with death animation
https://youtu.be/s5hsNINSdEw

BFB-117 - Death Fade Out

---

Assets/_BForBoss/_Character/Scripts/PlayerWallRunBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-141
Now pushes the player towards the wall direction when wall running, also some small code cleanup on wall running

BFB-141: Rotate towards wall direction on wall run

---

Assets/_BForBoss/Tests/Mocks/MockInputSettings.cs
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.InputSettings.cs
Assets/_BForBoss/_Core/InputActions/BFB_FirstPerson_InputActions.inputactions
Assets/_BForBoss/_Core/Prefabs/ControllerInputSettingsPanel.prefab
Assets/_BForBoss/_Core/Prefabs/MouseKeyboardInputSettingsPanel.prefab
Assets/_BForBoss/_Core/Scripts/Debug/DebugWindow.cs
Assets/_BForBoss/_Utility/Scripts/FreezeActionsUtility.cs
Assets/_BForBoss/_Utility/Scripts/IInputSettings.cs
Assets/_BForBoss/_Weapons/Scenes/GunRange.unity

https://perigongames.atlassian.net/browse/BFB-149
Part of a solution. PRing chunk by chunk so it's more digestable
- Setup UI Action Map
- Created SwapUIActionMap and SwapPlayerActionMap 
- 1. is for player movement
- 2. is for UI navigation

BFB-149: Setup UI Action map

---

Assets/_BForBoss/Tests/CharacterWallRunTests.cs
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.InputSettings.cs
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.ThirdPerson.cs
Assets/_BForBoss/_Core/Scripts/AmmunitionCountViewBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Debug/DebugWindow.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/GameplaySettingsViewBehaviour.cs
Assets/_BForBoss/_Leaderboard/Scripts/LeaderboardPanelBehaviour.cs
Assets/_BForBoss/_Leaderboard/Scripts/UploadPlayerScoreDataSource.cs
Assets/_BForBoss/_Leaderboard/Scripts/Username/InputUsername.cs
Assets/_BForBoss/_Leaderboard/Scripts/Username/SetUsernameViewModel.cs
Assets/_BForBoss/_UserInterface/Scripts/SliderBehaviour.cs
Assets/_BForBoss/_Utility/Scripts/PlayerPrefKeys.cs
Assets/_BForBoss/_Utility/Scripts/PostProcessingVolumeWeightTool.cs
Assets/_BForBoss/_Weapons/Scripts/WeaponBehaviour.cs

- Made all const caps
- EXCEPT ANALYTICS

Martin: Clean Up Const to be caps

---

Assets/_BForBoss/_Utility/Scripts/Editor/AttributeValidators.meta
Assets/_BForBoss/_Utility/Scripts/Editor/AttributeValidators/ResolveAttributeValidator.cs
Assets/_BForBoss/_Utility/Scripts/Editor/AttributeValidators/ResolveAttributeValidator.cs.meta
Assets/_BForBoss/_Utility/Scripts/Editor/PropertyDrawers/ResolverPropertyDrawer.cs
Assets/_BForBoss/_Utility/Scripts/PropertyAttributes/ResolverExample/ResolveTestScript.cs

https://perigongames.atlassian.net/browse/BFB-153
Created Inspector based message to indicate the field-declared structs with the `[Resolve]` attribute can't be visualized and should be amended.

BFB-153 Custom Validator Added

---

Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/AutoRifle.asset
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/Shotgun.asset
Assets/_BForBoss/_Weapons/Scripts/Weapons/Weapon.cs

https://perigongames.atlassian.net/browse/BFB-161
- Fixed the weapon spread. Using Angles instead. 

BFB-161: Fixed Weapon Spread implementation

---

Assets/_BForBoss/_Core/Prefabs/Checkpoint.prefab
Assets/_BForBoss/_Core/Scripts/Checkpoint.cs
Assets/_BForBoss/_Core/Scripts/Core.asmdef
Assets/_BForBoss/_Core/Scripts/Managers/BaseWorldManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/WeaponRaceCourseWorldManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/WeaponRaceCourseWorldManager.cs.meta
Assets/_BForBoss/_Core/Scripts/UserInterface/MouseKeyboardInputSettingsViewModel.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/PauseMenu.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/SettingsViewBehaviour.cs
Assets/_BForBoss/_Entities/Animation/DummyController.controller
Assets/_BForBoss/_Entities/Scripts/DummyTargetBehaviour.cs
Assets/_BForBoss/_Entities/Scripts/HealthbarViewBehaviour.cs
Assets/_BForBoss/_Entities/Scripts/LifeCycle.cs
Assets/_BForBoss/_Entities/Scripts/LifeCycleBehaviour.cs
Assets/_BForBoss/_Entities/Scripts/ScriptableObjects/HealthProperties.asset
Assets/_BForBoss/_LevelDesign/Scenes/WeaponRaceCourse.unity.meta
Assets/_BForBoss/_Utility/Scripts/Tags.cs
Assets/_BForBoss/_Weapons/Prefabs/NoPhysicsBullet.prefab
Assets/_BForBoss/_Weapons/Prefabs/PhysicsBullet.prefab
Assets/_BForBoss/_Weapons/Scripts/Bullets/NoPhysicsBulletBehaviour.cs
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Bullets/RifleBulletProperties.asset
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/AutoRifle.asset
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/Shotgun.asset
Assets/_BForBoss/_Weapons/Scripts/Weapons/WeaponBehaviour.cs
ProjectSettings/EditorBuildSettings.asset
ProjectSettings/TagManager.asset

https://perigongames.atlassian.net/browse/BFB-165
- Created new Weapons Race Course scene
- Added TriggerArea layer to checkpoints, and ignore that layer in bullets
- Added new WeaponsRaceCourse WorldManager
https://www.youtube.com/watch?v=RQszoCUIlZQ

BFB-165: Weapons Race Course 

---

Assets/Graphy - Ultimate Stats Monitor/Prefab Variants/Graphy_Variant_0.prefab
Assets/_BForBoss/_Character/Scenes/Sandbox.unity
Assets/_BForBoss/_Core/Scripts/Managers/BaseWorldManager.cs.meta
Assets/_BForBoss/_Core/Scripts/Managers/WeaponRaceCourseWorldManager.cs.meta
Assets/_BForBoss/_Core/Scripts/UserInterface/GameplaySettingsViewBehaviour.cs
Assets/_BForBoss/_Utility/Scripts/PlayerPrefKeys.cs
Assets/_BForBoss/_Weapons/Scenes/GunRange.unity
Assets/_BForBoss/_Weapons/Scripts/Weapons/WeaponBehaviour.cs
ProjectSettings/EditorBuildSettings.asset

https://perigongames.atlassian.net/browse/BFB-183
- Removed storing Graphy variables, since graphy loads after everything apparantly? causing everything to be null. 
- removed audio listener from scenes
- Fixed Raycasting for weaponBehaviour

BFB-183: Removed Graphy Saved State

---

Assets/_BForBoss/_Utility/Scripts/ObjectPooler.cs

https://perigongames.atlassian.net/browse/BFB-188
Should fix the object pooler scene switching bug, fps should be consistent after switching the scene now

BFB-184: Fix for object pooler and scene switching

---

Assets/_BForBoss/_Entities/Animation/DummyController.controller
Assets/_BForBoss/_Entities/Prefabs/Dummy.prefab

https://perigongames.atlassian.net/browse/BFB-179
- Fixed up animation transitions
- Faster Death animation
- Death does not change position anymore (unchecked root animation)
https://user-images.githubusercontent.com/5779541/153147932-3fcdba20-21b3-4496-bbe1-63fd3852f829.mp4

BFB-179: Fixed up Dummies in scene

---

Assets/_BForBoss/Tests/Mocks/MockWeaponProperties.cs
Assets/_BForBoss/Tests/Tests.asmdef
Assets/_BForBoss/_Entities/Prefabs/Dummy.prefab
Assets/_BForBoss/_Entities/Scripts/DummyTargetBehaviour.cs
Assets/_BForBoss/_Entities/Scripts/Entities.asmdef
Assets/_BForBoss/_Entities/Scripts/LifeCycle.cs
Assets/_BForBoss/_Entities/Scripts/LifeCycleBehaviour.cs
Assets/_BForBoss/_Entities/Scripts/ScriptableObjects/HealthProperties.asset
Assets/_BForBoss/_Weapons/Scripts/Equipment/EquipmentBehaviour.IEquipmentData.cs
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/AutoRifle.asset
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/SemiAutoRifle.asset
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/Shotgun.asset
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/WeaponScriptableObject.cs
Assets/_BForBoss/_Weapons/Scripts/Weapons.asmdef
Assets/_BForBoss/_Weapons/Scripts/Weapons/Weapon.cs
Assets/_BForBoss/_Weapons/Scripts/Weapons/WeaponsManager.cs

https://perigongames.atlassian.net/browse/BFB-194
- Added Enemy On Hit Audio
- Added Enemy On Kill Audio
- Added Weapon Shooting audio 
https://user-images.githubusercontent.com/5779541/156044429-0ea6bfa3-42ad-40f2-8d96-8734437061f7.mp4

BFB-194: Audio for weapons and enemy hit/kill

---

Assets/_BForBoss/_LevelDesign/Scenes/MS2_RaceCourse.unity

https://perigongames.atlassian.net/browse/BFB-221
GameObject of panel + TextMeshPro text

BFB-221: Instructional Text on MS2 map

---

Assets/_BForBoss/_Weapons/Scripts/Weapons/WeaponsManager.cs

https://perigongames.atlassian.net/browse/BFB-194
- Set Position of Gun sounds

BFB-194: Gun sound fix

---

Assets/_BForBoss/_Core/Prefabs/PostProcessingVolume.prefab
Assets/_BForBoss/_LevelDesign/Scenes/MS2_RaceCourse.unity

https://perigongames.atlassian.net/browse/BFB-225
Slow motion post processing was only implemented in GunRange scene, added to post processing prefab and tied up in MS2 scene

BFB-225 - Add slow mo post processing

---

Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.cs
Assets/_BForBoss/_Character/Scripts/PlayerDashBehaviour.cs
Assets/_BForBoss/_Character/Scripts/PlayerSlideBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-192
Fix bug in character movement audio. Removed event chaining in favor of just passing in one event as a reference. Confirmed to work in build.

BFB-192: Fix character movement audio bug

---

.gitignore
Assets/UniversalRenderPipelineGlobalSettings.asset.meta

*no ticket*
Hotfix for ignored meta files. This removes *.meta from the gitignore and adds whatever meta files git picked up after I did that

Fix for ignored metas

---

Assets/Editor/DevBuildScript.cs
ProjectSettings/EditorBuildSettings.asset

- remove deleted scene from BuildSettings
- throw build exception when the build is suppose to fail

Fix build script

---

ProjectSettings/EditorBuildSettings.asset

https://perigongames.atlassian.net/browse/BFB-245

BFB-245: Update EditorBuildSettings.asset

---

Assets/_BForBoss/Tests/CharacterDashTests.cs
Assets/_BForBoss/_LevelDesign/Scenes/MS2_RaceCourse.unity

https://perigongames.atlassian.net/browse/BFB-277
Fixed sort order of the menu ui

BFB-277: Settings menu bug fixed

---

Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.CameraMask.cs
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.CameraMask.cs.meta
Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.cs

https://perigongames.atlassian.net/browse/BFB-272
- Added camera culling mask to hide player model

BFB-272: Setup camera mask to hide Legs

---

Assets/_BForBoss/_Weapons/Scenes/GunRange.unity

https://perigongames.atlassian.net/browse/BFB-286
Just added scriptable objects to the weapon themselves

BFB-286: Melee on Weapon scene fix

---

ProjectSettings/EditorBuildSettings.asset

https://perigongames.atlassian.net/browse/BFB-354

BFB-354: Added MT_sandbox to editor

---

Assets/_BForBoss/_Character/Scripts/PlayerWallRunBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-360
Raycast wall running on eye height
https://youtu.be/p5-OzwXY2Js

BFB-360: Raycast on eye height and center body height

---

Assets/_BForBoss/_Core/Scripts/Enemies/EnemyShootingBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Enemies/FloatingEnemyAnimationBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Enemies/FloatingEnemyAnimationBehaviour.cs.meta
Assets/_BForBoss/_Core/Scripts/Enemies/FloatingTargetBehaviour.cs
Assets/_BForBoss/_Entities/Prefabs/FloatingEnemy.prefab
Assets/_BForBoss/_Entities/Scripts/EnemyBehaviour.cs
Assets/_BForBoss/_Entities/_Enemies/FlyingRobot/FlyingRobot.controller
Assets/_BForBoss/_Entities/_Enemies/FlyingRobot/FlyingRobot.controller.meta

https://perigongames.atlassian.net/browse/BFB-382
Integrated the Animation for Idle, Movement, Shoot

BFB-382: Floating AI Animation

---

.github/workflows/build.yml

remove macOs version
update Unity version

Add GitHub build action

---

Assets/_BForBoss/_LevelDesign/Scenes/WaveSandbox.unity
ProjectSettings/EditorBuildSettings.asset

https://perigongames.atlassian.net/browse/BFB-392
Added Kevin's scene into the EditorBuildSettings and updated the scene to use the new AdditiveWeaponsManager scene as well as resolve and null reference exception errors (to ensure the build works with it)

BFB-392 : Added WaveSandbox Scene into EditorBuildSettings

---

Assets/_BForBoss/_Weapons/Scripts/Weapons/WeaponAnimationController.cs

https://perigongames.atlassian.net/browse/BFB-407
Add script execution order flag to make it run after cinemachine brain, this fixes the jitter

BFB-407 : Weapon Jitter Fix

---

Assets/_BForBoss/_Character/Scripts/PlayerMovementBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Debug/DebugView/FreeRoamCameraDebugView.cs
Assets/_BForBoss/_Core/Scripts/Debug/DebugView/SceneSwitcherDebugView.cs
Assets/_BForBoss/_Core/Scripts/Debug/DebugWindow.cs
Assets/_BForBoss/_Utility/Scripts/FreeRoamCamera.cs

https://perigongames.atlassian.net/browse/BFB-374
- Unsubscribe the Lock Action Inputs
- Fix up the free roam debug view camera

BFB-374: Scene switching fixes

---

Assets/_BForBoss/_Core/Prefabs/Managers/EntityManager.prefab
Assets/_BForBoss/_Core/Prefabs/Managers/Equipment.prefab
Assets/_BForBoss/_Weapons/Scripts/Bullets/BulletBehaviour.cs
Assets/_BForBoss/_Weapons/Scripts/Bullets/BulletSpawner.cs
Assets/_BForBoss/_Weapons/Scripts/Bullets/NoPhysicsBulletBehaviour.cs
Assets/_BForBoss/_Weapons/Scripts/Editor/BulletSpawnerInspector.cs

https://perigongames.atlassian.net/browse/BFB-411
- Add support for layer mask field, specifically to be used by raycast bullets (previously, only physical bullets supported proper layers)
- Implement layer masks into relevant prefabs

BFB-411 : Fix Enemy Shooting one another

---

Assets/_BForBoss/_Character/Prefabs/PlayerRoot.prefab

https://perigongames.atlassian.net/browse/BFB-423
Removed collider from the mesh

BFB-423: Fix crouch 

---

Assets/_BForBoss/_Core/InputActions/BFB_FirstPerson_InputActions.inputactions
Assets/_BForBoss/_Core/Scripts/Managers/BaseWorldManager.cs
Assets/_BForBoss/_Utility/Scripts/PGInputSystem.cs

https://perigongames.atlassian.net/browse/BFB-431

BFB-431: Escape key to unpause

---

Assets/_BForBoss/_Character/PostProcessingVolume/DeathPostProcessingProfile.asset
Assets/_BForBoss/_Character/PostProcessingVolume/DeathPostProcessingProfile.asset.meta
Assets/_BForBoss/_Core/Prefabs/PostProcessingVolume.prefab
Assets/_BForBoss/_Core/Scenes/AdditiveUserInterfaceScene.unity
Assets/_BForBoss/_Core/Scripts/Enemies/EnemyContainer.cs
Assets/_BForBoss/_Core/Scripts/Managers/BaseWorldManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/StateManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/UserInterfaceManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/WaveManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/WaveSandboxWorldManager.cs
Assets/_BForBoss/_Core/Scripts/PlayerBehaviour.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/EndGameViewBehaviour.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/EndGameViewBehaviour.cs.meta
Assets/_BForBoss/_Core/Scripts/UserInterface/PauseViewBehaviour.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/UseCases.meta
Assets/_BForBoss/_Core/Scripts/UserInterface/UseCases/QuitGameUseCase.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/UseCases/QuitGameUseCase.cs.meta
Assets/_BForBoss/_Core/Scripts/UserInterface/UseCases/ResetGameUseCase.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/UseCases/ResetGameUseCase.cs.meta
Assets/_BForBoss/_Entities/Scripts/LifeCycle.cs
Assets/_BForBoss/_Entities/Scripts/LifeCycleBehaviour.cs
Assets/_BForBoss/_Entities/Scripts/PlayerHealthViewBehaviour.cs
Assets/_BForBoss/_Entities/Scripts/PlayerLifeCycleBehaviour.cs
Assets/_BForBoss/_Entities/Scripts/ScriptableObjects/PlayerHealthProperties.asset
Assets/_BForBoss/_Utility/Scripts/ObjectPooler.cs
Assets/_BForBoss/_Utility/Scripts/VisualEffectsManager.cs
Assets/_BForBoss/_Weapons/Scripts/Bullets/BulletSpawner.cs
Assets/_BForBoss/_Weapons/Scripts/Bullets/NoPhysicsBulletBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-371
This is basically the MVP for an end game cycle. There are a few things here and there that could use polish. But this ends and resets.
- End game cycle
- Added UI
- Set up reset in a few components to make the end game cycle work
- Added Death Screen Volume
https://www.youtube.com/watch?v=8faxf2issHE

BFB-371: End Game Cycle

---

Assets/_BForBoss/_Core/Prefabs/Managers/EnemySpawnerManager.prefab
Assets/_BForBoss/_Core/Prefabs/PostProcessingVolume.prefab
Assets/_BForBoss/_Core/Scripts/Enemies/EnemyShootingBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-413
Fixes 3 separate bugs
- Set the shoot animation when the AI Shoots
- AI Bullets damage the player
- End Game makes it black screen
https://user-images.githubusercontent.com/5779541/189645797-1016e7d1-5321-4644-a535-b3d077aec449.mp4

BFB-416: Shooting Animation Timing + Enemy can damage player

---

Assets/_BForBoss/_Core/Scripts/Debug/DebugView/DebugView.cs
Assets/_BForBoss/_Core/Scripts/Debug/DebugWindow.cs

https://perigongames.atlassian.net/browse/BFB-433

BFB-433: Fix Debug View

---

Assets/_BForBoss/_Core/Prefabs/UserInterface/WaveUICanvas.prefab
Assets/_BForBoss/_Core/Scripts/UserInterface/WaveViewBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-418

BFB-418: Fix up UI of Waves

---

Assets/_BForBoss/_Entities/Prefabs/EnemyBullet.prefab

https://perigongames.atlassian.net/browse/BFB-435
Increased bullet trail length and width

BFB-435: Changed Enemy Bullet Trail

---

Assets/_BForBoss/_Core/Scripts/Environment/EnemySpawnAreaBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Managers/EnemySpawnersManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/WaveManager.cs
Assets/_BForBoss/_Core/Scripts/WaveSystem/WaveModel.cs
Perigon/Logger.asset

https://perigongames.atlassian.net/browse/BFB-424
Wrap the debug logs

BFB-424: Wrap logging

---

Assets/_BForBoss/_Character/Scripts/PlayerMovementBehaviour.cs
Assets/_BForBoss/_Character/Scripts/PlayerSlowMotionBehaviour.cs
Assets/_BForBoss/_Core/Scripts/PlayerBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-441
- Added Pausing and resuming for tweening
https://user-images.githubusercontent.com/5779541/192077313-773ba30a-cf5b-4f9e-9b74-b6131a6facf0.mp4

BFB-441: Fix for pausing while tweening

---

Assets/_BForBoss/_Entities/Enemies/VFX.meta
Assets/_BForBoss/_Entities/Enemies/VFX/BulletSplash.meta
Assets/_BForBoss/_Entities/Enemies/VFX/BulletSplash/P_BulletSplash.prefab
Assets/_BForBoss/_Entities/Enemies/VFX/BulletSplash/P_BulletSplash.prefab.meta
Assets/_BForBoss/_Entities/Enemies/VFX/BulletSplash/SG_BulletSplash.shadergraph
Assets/_BForBoss/_Entities/Enemies/VFX/BulletSplash/SG_BulletSplash.shadergraph.meta
Assets/_BForBoss/_Entities/Enemies/VFX/BulletSplash/VFX_BulletSplash.vfx
Assets/_BForBoss/_Entities/Enemies/VFX/BulletSplash/VFX_BulletSplash.vfx.meta

https://perigongames.atlassian.net/browse/BFB-434
Created an effect to play when a bullet hits a surface.
Can be found under _BForBoss > _Entities > Enemies > VFX > BulletSplash
There is a prefab for the scaled version of the bullet splash (0.25 scale to match the enemy bullet)
There is also the VFX graph and the shader graph in the folder.

BFB-434: Created Bullet Splash VFX

---

Assets/_BForBoss/_Core/Scripts/Debug/DebugView/DebugView.cs
Assets/_BForBoss/_Core/Scripts/Debug/DebugView/FreeRoamCameraDebugView.cs
Assets/_BForBoss/_Core/Scripts/Debug/DebugView/PlayerPrefResetterDebugView.cs
Assets/_BForBoss/_Core/Scripts/Debug/DebugView/SceneSwitcherDebugView.cs
Assets/_BForBoss/_Core/Scripts/Debug/DebugWindow.cs

https://perigongames.atlassian.net/browse/BFB-453
When the gameview screen sizes change and Debug Windows begin to clip, a scroll view will now appear to ensure content is always readable/interactable

BFB-453 : DebugView windows use scrollviews

---

Assets/_BForBoss/_Core/Prefabs/UserInterface/TimerUICanvas.prefab
Assets/_BForBoss/_Core/Prefabs/UserInterface/TimerUICanvas.prefab.meta
Assets/_BForBoss/_Core/Scripts/Managers/WaveSandboxWorldManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/WeaponSandboxWorldManager.cs
Assets/_BForBoss/_Core/Scripts/TimerViewBehaviour.cs
Assets/_BForBoss/_Core/Scripts/TimerViewBehaviour.cs.meta

https://perigongames.atlassian.net/browse/BFB-463
Added Timer Canvas
Added Timer Logic
Added Timer logic to waveBasedWorldManager
https://user-images.githubusercontent.com/5779541/196089286-296cfb4e-75c8-461f-8271-7f1951fb3bea.mp4

BFB-463: Dev only Timer UI

---

Assets/_BForBoss/_Core/Scripts/Enemies/FloatingTargetBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Environment/DeathAreaBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Environment/EnemySpawnAreaBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Managers/WaveSandboxWorldManager.cs
Assets/_BForBoss/_Core/Scripts/TimerViewBehaviour.cs
Assets/_BForBoss/_Entities/Scripts/EnemyBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-467
- Update wave model at death
https://user-images.githubusercontent.com/5779541/196095560-ec95daa5-6d16-4d6e-b16b-c7576fe014b0.mp4

BFB-467: Update the wave model on death

---

Assets/_BForBoss/_Core/Scripts/Character/PlayerMovementBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Character/PlayerWallRunBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Environment/WallRunning/WallRunData.cs
Assets/_BForBoss/_Core/Scripts/Environment/WallRunning/WallRunSO.cs
Perigon/Logger.asset

https://perigongames.atlassian.net/browse/BFB-491
- Make some variables universal
- Make sure when moving wall to wall, the data get's transfered and updated
https://user-images.githubusercontent.com/5779541/219968394-f0b50eb5-73b5-4ebd-a498-d1f9b44a28ed.mp4

BFB-491: Wall Running Bug Fix

---

Assets/_BForBoss/Tests/CharacterMovementAudioTests.cs
Assets/_BForBoss/Tests/Mocks/MockCharacterMovement.cs
Assets/_BForBoss/_Core/Scripts/Character/CharacterMovementAudio.cs
Assets/_BForBoss/_Core/Scripts/Character/CharacterMovementAudioBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Character/PlayerDashBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Character/PlayerMovementBehaviour.CharacterMovement.cs
Assets/_BForBoss/_Core/Scripts/Character/PlayerMovementBehaviour.IGetPlayerTransform.cs
Assets/_BForBoss/_Core/Scripts/Character/PlayerMovementBehaviour.IGetPlayerTransform.cs.meta
Assets/_BForBoss/_Core/Scripts/Character/PlayerMovementBehaviour.IPlayerMovementStates.cs
Assets/_BForBoss/_Core/Scripts/Character/PlayerMovementBehaviour.IPlayerMovementStates.cs.meta
Assets/_BForBoss/_Core/Scripts/Character/PlayerMovementBehaviour.IWeaponBobIntensity.cs
Assets/_BForBoss/_Core/Scripts/Character/PlayerMovementBehaviour.IWeaponBobIntensity.cs.meta
Assets/_BForBoss/_Core/Scripts/Character/PlayerMovementBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Character/PlayerSlideBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Character/PlayerWallRunBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Managers/WeaponSceneManager.cs
Assets/_BForBoss/_Weapons/Scripts/Equipment/EquipmentBehaviour.cs
Assets/_BForBoss/_Weapons/Scripts/Weapons/MeleeWeaponBehaviour.cs
Assets/_BForBoss/_Weapons/Scripts/Weapons/WeaponAnimationController.cs
ProjectSettings/EditorBuildSettings.asset

https://perigongames.atlassian.net/browse/BFB-492
- Cut Down PlayerMovement+IPlayerMovement into separate interfaces based on needs, instead of generic properties (Use methods instead).
- PlayerDash/Slide/WallRun - No more injecting Actions into init. Use Delegate Pattern instead.

BFB-492: Refactor PlayerMovement + Related

---

Assets/_BForBoss/_Utility/Scripts/CustomPassVolumeWeightTool.cs

https://perigongames.atlassian.net/browse/BFB-503
- Create a new material and setting it, only in Unity Editor

BFB-503: Material Fix

---

Assets/_BForBoss/_Core/Scripts/EnergySystem.meta
Assets/_BForBoss/_Core/Scripts/EnergySystem/Data.meta
Assets/_BForBoss/_Core/Scripts/EnergySystem/Data/EnergyData.cs
Assets/_BForBoss/_Core/Scripts/EnergySystem/Data/EnergyData.cs.meta
Assets/_BForBoss/_Core/Scripts/EnergySystem/Data/EnergySO.cs
Assets/_BForBoss/_Core/Scripts/EnergySystem/Data/EnergySO.cs.meta
Assets/_BForBoss/_Core/Scripts/EnergySystem/Data/EnergySystemConfigurationData.cs
Assets/_BForBoss/_Core/Scripts/EnergySystem/Data/EnergySystemConfigurationData.cs.meta
Assets/_BForBoss/_Core/Scripts/EnergySystem/Data/EnergySystemConfigurationSO.cs
Assets/_BForBoss/_Core/Scripts/EnergySystem/Data/EnergySystemConfigurationSO.cs.meta
BForBoss.sln.DotSettings

https://perigongames.atlassian.net/browse/BFB-493
Created the initial data files for the Energy System and its corresponding Configuration
The data is meant to hold information about how much energy each Transaction holds and the rate at which it transfers to/from the player

BFB-493: Initial Data/ScriptableObject files for Energy System

---

Assets/_BForBoss/_Core/Scripts/EnergySystem/Data/EnergyData.cs
Assets/_BForBoss/_Core/Scripts/EnergySystem/EnergySystemBehaviour.cs
Assets/_BForBoss/_Core/Scripts/EnergySystem/EnergySystemBehaviour.cs.meta
Perigon/Logger.asset

https://perigongames.atlassian.net/browse/BFB-494
- Created the base system for Energy System

BFB-494: Energy System

---

Assets/_BForBoss/_Core/Scripts/Character/PlayerWallRunBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Environment/EnemySpawnAreaBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Managers/EnemySpawnersManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/WaveManager.cs
Assets/_BForBoss/_Core/Scripts/WaveSystem/WaveModel.cs
Assets/_BForBoss/_Utility/Scripts/Logger/Logger.cs

https://perigongames.atlassian.net/browse/BFB-502
Added a color parameter to our Logger Tool methods, so that people can more easily set colors to their logged messages

BFB-502: Add Color Param for the logger tool

---

Assets/_BForBoss/_Core/Scripts/Managers/BaseWorldManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/HUDManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/SandboxWorldManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/WeaponSceneManager.cs
Assets/_BForBoss/_Core/Scripts/PlayerBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-497

BFB-497: BaseWorld with Energy System

---

Assets/_BForBoss/_Weapons/Scenes/AdditiveWeaponManager.unity
Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/SingleShot.asset
Assets/_BForBoss/_Weapons/Scripts/Weapons/Weapon.cs
Assets/_BForBoss/_Weapons/Scripts/Weapons/WeaponBehaviour.FiringProjectiles.cs
Assets/_BForBoss/_Weapons/Scripts/Weapons/WeaponBehaviour.FiringRayCast.cs
Assets/_BForBoss/_Weapons/Scripts/Weapons/WeaponBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-508
- Remove the calculations of shooting projectile
- Going with 
1. shooting projectile from within the Player Collision Box
2. Shooting from the center of the camera.
https://user-images.githubusercontent.com/5779541/224515951-a36254c6-c00b-42f6-9db8-ea29a94f89ce.mp4

BFB-508: Fixing up Shooting inaccurate bug

---

Assets/_BForBoss/_Art/Enemies/VFX/BulletSplash/VFX_BulletSplash.vfx
Assets/_BForBoss/_Art/VFX/Base VFX Materials/S_PreMulti_VFX.shadergraph
Assets/_BForBoss/_Art/Weapons_Materials/BulletEnergyTrail.mat
Assets/_BForBoss/_Art/Weapons_Materials/BulletEnergyTrail.mat.meta
Assets/_BForBoss/_Art/Weapons_Materials/BulletTrail.mat
Assets/_BForBoss/_Art/Weapons_VFX/EnergyShotVFX.meta
Assets/_BForBoss/_Art/Weapons_VFX/EnergyShotVFX/VFX_EnergyMuzzle.vfx
Assets/_BForBoss/_Art/Weapons_VFX/EnergyShotVFX/VFX_EnergyMuzzle.vfx.meta
Assets/_BForBoss/_LevelDesign/Scenes/FullSandbox.unity
Assets/_BForBoss/_Shaders.meta
Assets/_BForBoss/_VFX.meta
Assets/_BForBoss/_Weapons/Prefabs/PhysicsEnergyBullet.prefab
Assets/_BForBoss/_Weapons/Prefabs/PhysicsEnergyBullet.prefab.meta
Assets/_BForBoss/_Weapons/Scenes/AdditiveWeaponManager.unity
ProjectSettings/EditorBuildSettings.asset

https://perigongames.atlassian.net/browse/BFB-507
Created a new muzzle flash and bullet train for the energy bullet. When a the bullet collides it uses the enemy bullet hit effect.
https://user-images.githubusercontent.com/94721502/227071832-39ab5c73-3316-4785-b3a1-b1dcd8a40b1c.mp4

BFB-507: New Weapon Muzzle, Bullet, and Hit effect

---

Assets/_BForBoss/_VFX/MS5_Boss_Shield/Scripts/SpawnShieldRipple.cs
Assets/_BForBoss/_Weapons/Scripts/Bullets/BulletBehaviour.ApplyDamage.cs

https://perigongames.atlassian.net/browse/BFB-526
- Added case to collide with shield
https://user-images.githubusercontent.com/5779541/228712707-fe98eaf8-3363-4f66-af79-8ac1f9546191.mp4

BFB-526: Bullet collision with shield

---

Assets/_BForBoss/_Core/Prefabs/Ring.prefab
Assets/_BForBoss/_Core/Prefabs/RingGrouping.prefab
Assets/_BForBoss/_Core/Scripts/Labor/RingSystem/RingBehaviour.cs
Assets/_BForBoss/_Utility/Scripts/RotateToFacePlayer.cs
Assets/_BForBoss/_Utility/Scripts/RotateToFacePlayer.cs.meta

https://perigongames.atlassian.net/browse/BFB-528
Update ring appearance so that text is more prominent and add in billboarding behavior

BFB-528: Ring billboarding

---

Assets/_BForBoss/_Core/Prefabs/Boss_Derek.meta
Assets/_BForBoss/_Core/Prefabs/Boss_Derek/DerekMissle.prefab
Assets/_BForBoss/_Core/Prefabs/Boss_Derek/DerekMissle.prefab.meta
Assets/_BForBoss/_Core/Prefabs/Boss_Derek/MissleLaunchers.prefab
Assets/_BForBoss/_Core/Prefabs/Boss_Derek/MissleLaunchers.prefab.meta
Assets/_BForBoss/_Core/Scripts/Boss/DerekMissileBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Boss/DerekMissileBehaviour.cs.meta
Assets/_BForBoss/_Core/Scripts/Boss/DerekMissileLauncherBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Boss/DerekMissileLauncherBehaviour.cs.meta
Assets/_BForBoss/_Core/Scripts/Managers/SandboxWorldManager.cs
Assets/_BForBoss/_Core/Scripts/Placeholders/ShootAtButtonBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Placeholders/ShootAtButtonBehaviour.cs.meta
Assets/_BForBoss/_LevelDesign/Scenes/FullSandbox.unity
Assets/_BForBoss/_Weapons/Scripts/Bullets/BulletSpawner.cs

https://perigongames.atlassian.net/browse/BFB-512
- Added Derek Missile Launcher
- Added Shoot to activate scripts
- Added new. room for Missile launching
- 
https://user-images.githubusercontent.com/5779541/232344267-bce6f746-4c38-48e9-8877-83a179661971.mp4

BFB-512: Missile Launcher

---

Assets/_BForBoss/_Core/Scripts/Boss/RotationalMovementBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-535
This is just to address @Gursaanj 's comment on the previous PR that got autosquashed. I think if we want the script to support nonphysical objects we should make a separate script for that, rather than having one that does both

BFB-535 Code Cleanup

---

Assets/_BForBoss/_Core/Scripts/Boss/DerekShieldBehaviour.cs
Assets/_BForBoss/_Utility/Scripts/Extensions.cs

https://perigongames.atlassian.net/browse/BFB-541
Set up derek shield behavior to launch the player with configurable settings for launch.
Tested against both just walking into the shield and enabling the shield when the player is inside it. If the player walks into it, their momentum will affect launch velocity. Otherwise, a minimum value will be used.

BFB-541: Launch Player from Shield

---

Assets/Plugins/Sirenix/Odin Inspector/Config/Resources/Sirenix/GlobalSerializationConfig.asset
Assets/_BForBoss/_Core/Prefabs/Ring.prefab
Assets/_BForBoss/_Core/Scripts/Labor/RingSystem/RingLaborManager.cs
Assets/_BForBoss/_Core/Scripts/Labor/RingSystem/RingSystem.cs
Assets/_BForBoss/_LevelDesign/Scenes/FullSandbox.unity
Packages/manifest.json
Packages/packages-lock.json

https://perigongames.atlassian.net/browse/BFB-553
https://perigongames.atlassian.net/browse/BFB-554
Remove physical collider from rings and remove unused system support - now only supports nested systems and standard (one ring at a time) systems

BFB-553/554 - Ring System Changes

---

Assets/_BForBoss/_Core/Scenes/AdditiveUserInterfaceScene.unity
Assets/_BForBoss/_Core/Scripts/Managers/SandboxWorldManager.cs

https://perigongames.atlassian.net/browse/BFB-558
- Updated Game Over Screen

BFB-558: Game Over Screen

---

Assets/_BForBoss/_Core/Scripts/Labor/RingSystem/RingBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Labor/RingSystem/RingLaborManager.cs

https://perigongames.atlassian.net/browse/BFB-563
Invoke panic helper when ring list or nested list (depending on type) is empty

Add panic helper to ring lists

---

Assets/_BForBoss/_Core/Scenes/AdditiveUserInterfaceScene.unity
Assets/_BForBoss/_UICore/Prefabs/Buttons/Rounded_Button.prefab
Assets/_BForBoss/_UICore/Prefabs/Buttons/Square_Button.prefab

https://perigongames.atlassian.net/browse/BFB-571
- Settings page scales
- Game Over Screen updated

BFB-571: Settings page scales

---

Assets/_BForBoss/_Art/Enemies/FlyingRobot/ShootVFX/S_EnemyProjectileMain.shadergraph
Assets/_BForBoss/_Core/Prefabs/Ring.prefab
Assets/_BForBoss/_Core/Scripts/Labor/RingSystem/RingBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Labor/RingSystem/RingLaborManager.cs
Assets/_BForBoss/_Core/Scripts/Labor/RingSystem/RingSystem.cs
Assets/_BForBoss/_LevelDesign/Scenes/DerekFlowSandbox.unity

https://perigongames.atlassian.net/browse/BFB-572
Change ring color with every labor. Also expose the main color of the shader and set up decent looking colors in the DerekFlowSandbox scene

BFB-572 - Ring System Color Changing

---

Assets/_BForBoss/_Core/Scripts/Boss/DerekBossManager.cs

https://perigongames.atlassian.net/browse/BFB-593
Fix animator bug by resetting trigger calls

BFB-593 - Reset animators on reset

---

Assets/_BForBoss/_Core/Scenes/AdditiveUserInterfaceScene.unity
Assets/_BForBoss/_Core/Scripts/Boss/DerekContextManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/BaseWorldManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/UserInterfaceManager.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/EndGameViewBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-588
Show victory screen
Logic - On End Game, assume it's win condition, on Death assume it's lose condition

BFB-588: Victory screen on boss death

---

Assets/Graphy - Ultimate Stats Monitor/Prefab Variants/Graphy_Variant_0.prefab
Assets/_BForBoss/_Core/Scripts/Boss/DerekContextManager.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/TelemetricsViewBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-595
- Setting up Telemetry settings.

BFB-595: Telemetry settings

---

Assets/_BForBoss/_Core/Scenes/AdditiveHUDScene.unity
Assets/_BForBoss/_Core/Scripts/Boss/DerekMissileLauncherBehaviour.cs
Assets/_BForBoss/_Core/Scripts/HUD/IncomingAttackIndicatorView.cs
Assets/_BForBoss/_Core/Scripts/HUD/IndicatorBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Managers/BaseWorldManager.cs
Assets/_BForBoss/_Core/Scripts/Managers/HUDManager.cs
Assets/_BForBoss/_LevelDesign/Scenes/FullSandbox.unity

https://perigongames.atlassian.net/browse/BFB-596
- Bug Fix Reset Indicator on reset
- Added indicator View on AdditiveHUDView

BFB-596: Reset Indicator

---

Assets/_BForBoss/_Core/Prefabs/Boss_Derek/DerekMissile.prefab
Assets/_BForBoss/_Core/Scripts/Boss/DerekMissileBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-598
Add knockback to player when hit by missile Knockback multiplier can be scaled by designers
https://github.com/PerigonGames/BForBoss/assets/23490604/527a94b3-7977-4bf9-ad13-4b559790c366

BFB-598 : Add knockback to Missile

---

Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
Assets/_BForBoss/_Core/Prefabs/Boss_Derek/DerekMissile.prefab
Assets/_BForBoss/_Core/Prefabs/Boss_Derek/DerekV2.prefab
Assets/_BForBoss/_Core/Prefabs/Boss_Derek/MissleLaunchers.prefab
Assets/_BForBoss/_Core/Prefabs/GameStateAudioListener.prefab
Assets/_BForBoss/_Core/Prefabs/GameStateAudioListener.prefab.meta
Assets/_BForBoss/_Core/Prefabs/Ring.prefab
Assets/_BForBoss/_Core/Scripts/Audio/GameStateAudioListener.cs
Assets/_BForBoss/_Core/Scripts/Audio/GameStateAudioListener.cs.meta
Assets/_BForBoss/_Core/Scripts/Boss/DerekBossManager.cs
Assets/_BForBoss/_Core/Scripts/Boss/DerekHealthBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Boss/DerekMissileBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Boss/DerekMissileLauncherBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Boss/DerekShieldBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Environment/PlayerTriggerAreaEffect.cs
Assets/_BForBoss/_Core/Scripts/Labor/RingSystem/RingBehaviour.cs
Assets/_BForBoss/_Core/Scripts/Labor/RingSystem/RingLaborManager.cs
Assets/_BForBoss/_LevelDesign/Scenes/DerekFlowSandbox.unity
Assets/_BForBoss/_VFX/MS5_Boss_Shield/Prefabs/VFX_Boss_Shield.prefab
Assets/_BForBoss/_VFX/MS5_Boss_Shield/Scripts/SpawnShieldRipple.cs

https://perigongames.atlassian.net/browse/BFB-573
https://perigongames.atlassian.net/browse/BFB-574
https://perigongames.atlassian.net/browse/BFB-575
https://perigongames.atlassian.net/browse/BFB-576
https://perigongames.atlassian.net/browse/BFB-577
https://perigongames.atlassian.net/browse/BFB-578
https://perigongames.atlassian.net/browse/BFB-579
https://perigongames.atlassian.net/browse/BFB-580
https://perigongames.atlassian.net/browse/BFB-582
Add audio integration. A few things to note: 
- First, I didn't get to jump pad integration. I'm not entirely clear where to add that.
- Code is set up for splash sfx, but not implemented in any scenes/prefabs
- Audio is NOT mastered. Stuff is very loud or very quiet. Distance spatialization needs to be tweaked as …

Audio Integration

---

Assets/_BForBoss/_Core/Prefabs/Boss_Derek/DerekMissile.prefab
Assets/_BForBoss/_Core/Prefabs/IndicatorHUD/Indicator.prefab
Assets/_BForBoss/_Core/Scripts/HUD/IndicatorBehaviour.cs

https://perigongames.atlassian.net/browse/BFB-[TICKET NUMBER]

Missile balancing

---

Assets/_BForBoss/_Core/Prefabs/Boss_Derek/DerekMissile.prefab
Assets/_BForBoss/_Core/Scripts/Managers/BaseWorldManager.cs
Assets/_BForBoss/_Core/Scripts/UserInterface/Tutorial/TutorialViewsManager.cs

https://perigongames.atlassian.net/browse/BFB-[TICKET NUMBER]

Tutorial Changes

---

Assets/_BForBoss/_Core/Prefabs/Managers/Equipment.prefab
Assets/_BForBoss/_Weapons/Scenes/AdditiveWeaponManager.unity

https://perigongames.atlassian.net/browse/BFB-[TICKET NUMBER]
Removes the Automatic and Shotgun Weapon behaviour from the EquipmentManager. So that the player cannot switch weapons

Remove Automatic and Shotgun Weapon Behavior

---

Assets/_BForBoss/_Core/Prefabs/Boss_Derek/Cole_DerekPhase_1.asset
Assets/_BForBoss/_Core/Prefabs/Boss_Derek/Cole_DerekPhase_3.asset

Turns out we changed the wrong DerekPhaseSO file before making the first build. Made those changes again as well
- Changed Timer for phase 3 rings to 70 seconds
- Changed all phase rotation rates to be more balanced
- Changed Phase 1 rings to have more variety

Demo Tuning Pass 1

---

Assets/ECM2/Source/Characters/Character.cs
Assets/_BForBoss/_Core/Scripts/Environment/JumpPad.cs

https://perigongames.atlassian.net/browse/BFB-[TICKET NUMBER]

Reset Jump Count
